### ISSUE TITLE
Add moar tests

### ISSUE THREAD

**Issue by rpearce** [The-Iron-Masters/trackin-dollaz#28]
Given I have access to a list of tasks
I want to be able to edit that individual item

When I click the edit button for an item
I should be able to edit each individual field

Scenario: "Successful submit"
When I make changes
And I click "Save"/"Update"/"Submit"
I should see my changes reflected in the list
I should not see the editable fields

Scenario: "Failing submit"
When I make changes that are invalid
And I click "Save"/"Update"/"Submit"
I should see an error displayed on the screen informing me of what the problem is
I should still see the form fields
When I make the the correct updates
And I re-submit the form
I should see my changes reflected in the list

- [x] Tests need to be moar
- [x] Tests need to be great

**Comment by ryanmcgov** [comment]
Groovy

**Comment by rpearce** [comment]
Good word usage 



—
Robert Pearce

http://www.robertwpearce.com

https://www.linkedin.com/in/robertwpearce



m-US: 1.843.568.9080

m-UK: +44 7477 424374
